apiVersion: v1
{{- if .Values.configMap.enabled }}
kind: ConfigMap
metadata:
  name: {{ include "eks-cloudforge-app.configMapName" . }}
  labels:
    {{- include "eks-cloudforge-app.labels" . | nindent 4 }}
data:
  {{- include "eks-cloudforge-app.configMapData" . | nindent 2 }}
{{- end }}
