apiVersion: v1
{{- if .Values.secrets.enabled }}
kind: Secret
metadata:
  name: {{ include "eks-cloudforge-app.secretName" . }}
  labels:
    {{- include "eks-cloudforge-app.labels" . | nindent 4 }}
  annotations:
    {{- include "eks-cloudforge-app.annotations" . | nindent 4 }}
type: Opaque
data:
  # Secret data (base64 encoded)
  {{- include "eks-cloudforge-app.secretData" . | nindent 2 }}
{{- end }}
